-- MySQL Script generated by MySQL Workbench
-- Thu Jun  2 19:44:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Clinica` ;

-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinica` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `Clinica` ;

-- -----------------------------------------------------
-- Table `Ambulatorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ambulatorios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Ambulatorios` (
  `nroa` INT NOT NULL,
  `andar` INT(3) NOT NULL,
  `capacidade` SMALLINT(30) NULL,
  PRIMARY KEY (`nroa`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Consultas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Consultas` (
  `codm` INT NOT NULL,
  `codp` INT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  PRIMARY KEY (`data`, `hora`, `codm`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Funcionarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Funcionarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Funcionarios` (
  `codf` INT NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `idade` SMALLINT(3) NOT NULL,
  `cidade` VARCHAR(30) NULL,
  `CPF` INT(11) NOT NULL,
  `salario` INT(10) NULL,
  `cargo` VARCHAR(20) NULL,
  `nroa` INT NULL,
  PRIMARY KEY (`codf`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Medicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Medicos` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Medicos` (
  `codm` INT NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `idade` SMALLINT(3) NOT NULL,
  `especialidade` CHAR(20) NULL,
  `CPF` INT(11) NOT NULL,
  `cidade` VARCHAR(30) NULL,
  `nroa` INT NULL,
  PRIMARY KEY (`codm`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pacientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Pacientes` (
  `codp` INT NOT NULL,
  `nome` VARCHAR(40) NOT NULL,
  `idade` SMALLINT(3) NOT NULL,
  `cidade` VARCHAR(30) NULL,
  `CPF` INT(11) NOT NULL,
  `doenca` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`codp`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
